### ISSUE TITLE
Log Severity Ändern für "org.springframework.*"

### ISSUE THREAD

**Issue by greyshine** [jeschu/dirkboot#1]
Bitte das Logging für ````org.springframework.*```` auf ````INFO```` setzen.
Dies bitte per externer, einzelner Log-Konfigurationsdatei.

**Comment by jeschu** [comment]
Gelöst mit Commit f3aff566e1a42ed629e700e342945a311ae87a64 im master branch

**Comment by jeschu** [comment]
Kannst Du nicht im master Branch pushen?
